services:
  deploydash:
    image: docker.io/m4rtinkalenda/depdash:latest
    container_name: deploydash-backend
    ports:
      - "8080:8080"
    volumes:
      - "./db/data:/usr/src/app/db/data"
    restart: unless-stopped
    networks:
      - deploydash-net

networks:
  deploydash-net:
    driver: bridge
